# Generated by Django 2.1.2 on 2018-10-24 21:07

from django.db import migrations
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagefield.fields.ImageField(blank=True, default='default.jpg', height_field='image_height', upload_to='profile_pics', verbose_name='Profile Image', width_field='image_width'),
        ),
    ]
