# Generated by Django 2.1.2 on 2018-10-25 23:18

from django.db import migrations
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181024_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagefield.fields.ImageField(default='default.jpg', height_field='image_height', upload_to='profile_pics', verbose_name='Profile Image', width_field='image_width'),
        ),
    ]
