# Generated by Django 2.1.2 on 2018-11-08 22:42

from django.db import migrations
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagefield.fields.ImageField(blank=True, height_field='image_height', upload_to='post_pics', verbose_name='Main Image / Thumbnail', width_field='image_width'),
        ),
    ]
